# Generated by Django 5.2.6 on 2025-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tag', models.BooleanField()),
                ('views', models.IntegerField()),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
