# Generated by Django 5.2.6 on 2025-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tag', models.BooleanField(blank=True, default=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['header'],
            },
        ),
    ]
