# Generated by Django 5.2.6 on 2025-09-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
